CC = clang
CFLAGS = -Wall -Wextra -Werror

all: Colleen Grace Sully

Colleen: Colleen.c
    $(CC) $(CFLAGS) -o Colleen Colleen.c

Grace: Grace.c
    $(CC) $(CFLAGS) -o Grace Grace.c

Sully: Sully.c
    $(CC) $(CFLAGS) -o Sully Sully.c

clean:
    rm -f Colleen Grace Sully

re: clean all
